package com.example.gbtest08

import android.os.Bundle
import android.view.MenuItem
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class ReportActivity : AppCompatActivity() {
    private var reportTextView: TextView? = null
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_report)
        supportActionBar!!.setDisplayHomeAsUpEnabled(true)
        title = "Report"
        reportTextView = findViewById(R.id.reportTextView)

        // Display the report
        displayReport()
    }

    private fun displayReport() {
        // Generate and display the report
        // Replace this with your actual report generation logic
        val report = """
            Sample Report
            
            This is a sample report generated by the application. Replace this with your actual report generation logic.
            """.trimIndent()
        reportTextView!!.text = report
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        if (item.itemId == android.R.id.home) {
            onBackPressed()
            return true
        }
        return super.onOptionsItemSelected(item)
    }
}